### ISSUE TITLE
Amazing sketch, thanks for sharing. Adding esp-dsp support for hardware accerated FFTs?

### ISSUE THREAD

**Issue by mrcodetastic** [donnersm/BluetoothAnalyzer#1]
Hello. I noticed this project and look forward to trying it out on an ESP32S3 and using an LED matrix instead.

I just wanted to inform you that the ESP32-S3 has additional DSP related CPU SIMD instructions that coud materially improve the FFT throughput. As such, I was wondering if you ever had plans to assess the esp32-dsp library and see if this project works even better when using a S3 SoC.

**Comment by donnersm** [comment]
I wasn’t planning on it. But who knows…. Might do that in the future.

**Comment by mrcodetastic** [comment]
Ok cool. I might give it a crack then!
